apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
spec:
  replicas: 3  # Set the desired number of replicas
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: prima
        image: prima:v1  # Replace with your Docker image and tag
        ports:
        - containerPort: 8080  # Specify the port on which your API server is running
